-- these are generated the db objects generated by "configured_test_dbt_core.sql"

CREATE OR REPLACE VIEW self_tests_public_tests.dot_model__ancview_pregnancy
AS SELECT x.patient_id,
    x.value
   FROM ( VALUES ('patient-id1'::text,'1'::text), (NULL::text,'2'::text)) x(patient_id, value);

CREATE OR REPLACE VIEW self_tests_public_tests.tr_dot_model__ancview_pregnancy_not_null_patient_id
AS SELECT dot_model__ancview_pregnancy.patient_id,
    dot_model__ancview_pregnancy.value
   FROM self_tests_public_tests.dot_model__ancview_pregnancy
  WHERE dot_model__ancview_pregnancy.patient_id IS NULL;

CREATE OR REPLACE VIEW self_tests_public_tests.dot_model__fpview_registration
AS SELECT x.uuid,
    x.value
   FROM ( VALUES ('patient-id1'::text,'1'::text), ('patient_id2'::text,'2'::text), ('patient_id3'::text,'-3'::text)) x(uuid, value);

CREATE OR REPLACE VIEW self_tests_public_tests.tr_dot_model__fpview_registration_value
AS SELECT array_agg(dot_model__fpview_registration.uuid) AS uuid_list
   FROM self_tests_public_tests.dot_model__fpview_registration
  WHERE dot_model__fpview_registration.value::character varying::text ~~ '-%'::text
 HAVING count(*) > 0;