CREATE OR REPLACE VIEW public.useview_assessment_modified_muso
AS SELECT --patient assessment for child 5over
	uuid AS form_uuid,
    reported_by_parent AS chw_area_uuid,
    reported_by AS chw_uuid,
    -- family_uuid,
    form AS form_name,
    assessment_time,
    when_illness,
    assessment_time = 'c_assessment_time_1'::text AND (when_illness = ANY (ARRAY['c_when_illness_1'::text, 'c_when_illness_2'::text, 'c_when_illness_3'::text, 'c_when_illness_4'::text])) OR (assessment_time = ANY (ARRAY['c_assessment_time_2'::text, 'c_assessment_time_3'::text, 'c_assessment_time_4'::text])) AND (when_illness = ANY (ARRAY['c_when_illness_1'::text, 'c_when_illness_2'::text, 'c_when_illness_4'::text])) AS assessment_within_24h,
    -- COALESCE(NULLIF(s_assess_date, ''::text)::date, date_trunc('day'::text, reported)::date) AS reported_day,
    has_danger_sign,
    has_ref_danger_sign,
    accompany_refer_cscom ,
    has_mal_danger_sign,
    malaria_tdr_done,
    malaria_tdr_not_done,
    child_temperature_pre_chw,
    malaria_tdr_result,
  	patient_age_in_months,
  	malaria_act_dosage,
  	'':: text as diarrhea_stools_a_day,
  	'':: text as diarrhea_give_zinc,
  	'':: text as diarrhea_not_give_zinc,
  	'':: text as diarrhea_zinc_dosage,
  	'':: text as fast_breathing ,
  	'':: text as ari_have_cough,
  	'':: text as ari_give_amox,
  	'':: text as ari_not_give_amox,
  	'':: text as ari_give_amox_dosage,
  	'':: text as nutri_color_shakir ,
  	'':: text as nutri_give_vitamina,
  	'':: text as nutri_not_give_vitamina,
  	'':: text as nutri_give_albendazole,
  	'':: text as nutri_give_enriched_flour,
  	'':: text as nutri_not_give_enriched_flour,
  	'':: text as nutri_give_vitamina_dosage,
  	'':: text as nutri_give_albendazole_dosage,
  	-- s_fever as fever,
  	give_paracetamol_dosage,
  	malaria_give_act,
  	'':: text as ari_receive_honey,
  	'':: text as ari_receive_eucalyptus,
  	'':: text as diarrhea_give_ors,
  	'':: text as ari_receive_lemon,
	-- get_muso_reporting_month(COALESCE(NULLIF(formview_assessment_over_5.s_assess_date, ''::text)::date, date_trunc('day'::text, formview_assessment_over_5.reported)::date)) AS report_month,
	child_temperature,
	refer_to_cscom,
	accompany_to_cscom,
	patient_age_in_years,
	patient_age_in_days,
	'':: text as treat_diarrhea,
	'':: text as treat_malnutrition,
	-- s_fever_within_24_48,
    patient_sex,
    -- date_of_birth,
	patient_id,
	-- has_covid19_danger_sign,
	-- has_covid19_exposure_factors,
	-- s_resp_team_monitored,
	-- has_risk_factors,
	tdr_done,
	tdr_result,
	how_child_found,
	'':: text as diarrhea_not_give_ors,
	give_paracetamol,
	malaria_not_give_act,
	''::  text as ref_danger_sign_diarrhea_more_than_14_days,
	''::  text as ref_danger_sign_blood_in_stools,
	''::  text as treat_ari,
	''::  text as ref_danger_sign_red_shakir_strip,
	-- cat
    ''::text AS s_acc_tdr_not_done,
    ''::text AS ref_tdr_not_done,
    ''::text AS rp_did_place_suppository,
    ''::text AS rp_did_admin_artesunate_dosage,

    -- added columns to impact views
	ref_danger_sign_severe_jaundice,
	next_visit
	-- next_visit_5_days,
	-- next_visit_7_days,
    -- next_visit_covid_malaria_mult,
	-- next_visit_diarrhea,
	-- next_visit_ari,
	-- next_visit_malnutrition


   FROM formview_assessment_over_5
UNION ALL
 SELECT --patient assessment for child under5
	uuid AS form_uuid,
    reported_by_parent AS chw_area_uuid,
    reported_by AS chw_uuid,
    -- family_uuid AS clinic_uuid,
    form AS form_name,
    assessment_time,
    when_illness,
    assessment_time = 'c_assessment_time_1'::text AND (when_illness = ANY (ARRAY['c_when_illness_1'::text, 'c_when_illness_2'::text, 'c_when_illness_3'::text, 'c_when_illness_4'::text])) OR (assessment_time = ANY (ARRAY['c_assessment_time_2'::text, 'c_assessment_time_3'::text, 'c_assessment_time_4'::text])) AND (when_illness = ANY (ARRAY['c_when_illness_1'::text, 'c_when_illness_2'::text, 'c_when_illness_4'::text])) AS assessment_within_24h,
    -- COALESCE(NULLIF(s_assess_date, ''::text)::date, date_trunc('day'::text, reported)::date) AS reported_day,
   	has_danger_sign,
    has_ref_danger_sign ,
    accompany_refer_cscom,
    has_mal_danger_sign,
    malaria_tdr_done ,
    malaria_tdr_not_done ,
    child_temperature_pre_chw,
    malaria_tdr_result,
  	patient_age_in_months,
  	malaria_act_dosage ,
  	diarrhea_stools_a_day,
  	diarrhea_give_zinc ,
  	diarrhea_not_give_zinc ,
  	diarrhea_zinc_dosage,
  	fast_breathing ,
  	ari_have_cough,
  	ari_give_amox,
  	ari_not_give_amox,
  	ari_give_amox_dosage,
  	nutri_color_shakir,
  	nutri_give_vitamina,
  	nutri_not_give_vitamina,
  	nutri_give_albendazole,
  	nutri_give_enriched_flour,
  	nutri_not_give_enriched_flour,
  	nutri_give_vitamina_dosage,
  	nutri_give_albendazole_dosage,
  	-- s_fever as fever,
  	give_paracetamol_dosage,
  	malaria_give_act,
  	ari_receive_honey,
  	ari_receive_eucalyptus,
  	diarrhea_give_ors,
  	ari_receive_lemon,
	-- get_muso_reporting_month(COALESCE(NULLIF(formview_assessment.s_assess_date, ''::text)::date, date_trunc('day'::text, formview_assessment.reported)::date)) AS report_month,
    child_temperature,
	refer_to_cscom,
	accompany_to_cscom,
	patient_age_in_years,
	patient_age_in_days,
	treat_diarrhea,
	treat_malnutrition,
	-- s_fever_within_24_48,
    patient_sex,
    -- date_of_birth,
	patient_id,
	-- has_covid19_danger_sign,
	-- has_covid19_exposure_factors,
	-- s_resp_team_monitored,
	-- has_risk_factors,
	tdr_done,
	tdr_result,
	how_child_found,
	diarrhea_not_give_ors,
	give_paracetamol,
	malaria_not_give_act,
	ref_danger_sign_diarrhea_more_than_14_days,
	ref_danger_sign_blood_in_stools,
	treat_ari,
	ref_danger_sign_red_shakir_strip,
	-- cat,
    s_acc_tdr_not_done,
    ref_tdr_not_done,
    rp_did_place_suppository,
    rp_did_admin_artesunate_dosage,

    -- added columns to impact views
	ref_danger_sign_severe_jaundice,
	next_visit
	-- next_visit_5_days,
	-- next_visit_7_days,
    -- next_visit_covid_malaria_mult,
	-- next_visit_diarrhea,
	-- next_visit_ari,
	-- next_visit_malnutrition

    FROM formview_assessment ;
